=== josephmate/tagged-flashcards/flashcards.dtd
<!ELEMENT flashcards	(flashcard)>
<!ELEMENT flashcard		(front, back, tags)>
<!ELEMENT tags			(tag)>
<!ELEMENT tag			(#PCDATA)>
<!ELEMENT front			(#PCDATA)>
<!ELEMENT back			(#PCDATA)>

=== josephmate/tagged-flashcards/testinput.xml
<!DOCTYPE flashcards SYSTEM "flashcards.dtd">
<flashcards>
	<flashcard>
		<front>to say</front>
		<back>hablar</back>
		<tags>
			<tag>regular ar</tag>
			<tag>regular</tag>
			<tag>verb</tag>
		</tags>
	</flashcard>
	<flashcard>
		<front>to wash yourself</front>
		<back>lavarse</back>
		<tags>
			<tag>reflexive</tag>
			<tag>regular ar</tag>
			<tag>regular</tag>
		</tags>
	</flashcard>
</flashcards>
